from environs import Env

env = Env()

ZADARMA_API_KEY = env("ZADARMA_API_KEY")
ZADARMA_API_SECRET = env("ZADARMA_API_SECRET")

TELEGRAM_API_TOKEN = env("TELEGRAM_API_TOKEN")

ZADARMA_NUMBER = env("ZADARMA_NUMBER")
SIP = env("SIP")

INNER_NUMBER = env("INNER_NUMBER")
OUTER_NUMBER = env("OUTER_NUMBER")
